In [1]:
import numpy


In [2]:
numpy.__version__

'1.24.3'

In [3]:
numpy?

## CREATION A 1D ARRAY

In [4]:
import numpy as np

#array of integers
arr_1 = np.array([1,2,3,4,5])
print(arr_1 ," type : " , type(arr_1), " dimension : ", np.ndim(arr_1))

#array of floats
arr_2 = np.array([1.0,2.25,3.5])
print(arr_2 ,  type(arr_2), np.ndim(arr_2))

[1 2 3 4 5]  type :  <class 'numpy.ndarray'>  dimension :  1
[1.   2.25 3.5 ] <class 'numpy.ndarray'> 1


## CREATING A 2D ARRAY

In [5]:
arr_3 = np.array([  
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                ])

print(arr_3 ," type : " , type(arr_3), " dimension : ", np.ndim(arr_3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]  type :  <class 'numpy.ndarray'>  dimension :  2


## CREATING A 3D ARRAY

In [6]:
arr_3d = np.array([    
                        [  
                           [1.1, 2.2], 
                           [3.3, 4.4]
                        ]  , 
                        [
                           [5.5, 6.6], 
                           [7.7, 8.8]
                        ]    
                  ])
print(arr_3d ," type : " , type(arr_3d), " dimension : ", np.ndim(arr_3d))

[[[1.1 2.2]
  [3.3 4.4]]

 [[5.5 6.6]
  [7.7 8.8]]]  type :  <class 'numpy.ndarray'>  dimension :  3


## MATHEMATICAL FUNCTIONS

In [7]:
np.pi

3.141592653589793

In [8]:
# create an array of values between 0 and 2*pi
x = np.linspace(0,2*np.pi,100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [9]:
#calculate the sine of each element in array
y = np.sin(x)
print("Sine of each element: \n\n",y)

#calculate the exponential of each element in the array
z = np.exp(x)
print("\n\nExponential of each element:\n\n",z)

Sine of each element: 

 [ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01


## BASIC ARITHMETIC

In [10]:
#create 2 arrays of same shape
x = np.array([1,2,3])
y = np.array([4,5,6])

#add the arrays element-wise
a = x+y
print("Addition:",a)

#subtract the arrays element-wise
s = x-y
print("Subtraction:",s)

#multilply the arrays elements-wise
m = x*y
print("Multiplication:",m)

#divide the arrays elements-wise
d = x/y
print("Division:",d)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


## LINEAR ALGEBRA

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Matrix product of the two matrices
ma = np.dot(x,y)
print("Matrix Multiplication:",ma)

#inverse of a matrix
inv = np.linalg.inv(x)
print("Inverse of matrix:\n",inv)

#Eigenvalues and eigenvectors of a matrix
v , u = np.linalg.eig(x)
print("Eigen values:",v)
print("Eigen vectors:\n",u)

Matrix Multiplication: [[19 22]
 [43 50]]
Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigen values: [-0.37228132  5.37228132]
Eigen vectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## SATISTICAL FUNCTIONS

In [12]:
#create an array of random values
x = np.random.normal(0,1,10)
print("Array:\n",x)

#mean of the values in the array
y = np.mean(x)
print("\nMean:",y)

#median of the values in the array
z = np.median(x)
print("Median:",z)

#Standard deviation of the values in the array
w = np.std(x)
print("standard deviation:",w)

#Variance of the values in the array
v = np.var(x)
print("Variance:",v)

Array:
 [-0.62326979 -1.87222847  1.29291186 -0.4245859   0.55603056  1.00586725
 -0.08796747 -0.39968074 -0.2916113  -1.41044921]

Mean: -0.22549831876508059
Median: -0.34564601853908716
standard deviation: 0.938079420507933
Variance: 0.8799929991804994


## SORTING AND SEARCHING

In [13]:
#create an array of random values
x = np.random.randint(0,10,10)
print("Array:",x)

#sort the array in ascending order
y = np.sort(x)
print("Array in ascending array:",y)

#sort the array by index
z = np.argsort(x)
print("Array sorted by index:",z)

#search for the index of a specific value in the array
w = np.where(x == 7)
print("Index of the given value:",w)

Array: [8 3 6 3 2 2 9 5 5 8]
Array in ascending array: [2 2 3 3 5 5 6 8 8 9]
Array sorted by index: [4 5 1 3 7 8 2 0 9 6]
Index of the given value: (array([], dtype=int64),)


## BROADCASTING

In [14]:
#array of values
x = np.array([1,2,3])

#add a scalar value to each element in the array
y = x+1
print("Scalar value addition:\n",y)

#add a row vector to a matrix
z = np.array([[1,2,3],[4,5,6]])
w = np.array([1,2,3])
u = z +w

print("Vector addition:\n",u)

Scalar value addition:
 [2 3 4]
Vector addition:
 [[2 4 6]
 [5 7 9]]
